import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/components/Header'
import Provider from '@/redux/Provider'
import UserProvider from '@/components/UserProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <UserProvider>
            <Header/>
            {children}
          </UserProvider>
        </Provider>
      </body>
    </html>
  )
}
