import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/components/Header'
import Provider from '@/redux/Provider'
import UserProvider from '@/components/UserProvider'
import { ToastContainer } from 'react-toastify';
import MessageProvider from '@/components/MessageProvider'
import 'react-toastify/dist/ReactToastify.css';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <UserProvider>
            <MessageProvider>
              <Header/>
              {children}
            </MessageProvider>
          </UserProvider>
        </Provider>
        <ToastContainer 
          position="bottom-center"
          autoClose={5000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="light"
        />
      </body>
    </html>
  )
}
